defaults.pcm.rate_converter "speexrate_medium"
pcm.!default
{
    type asym
    playback.pcm {
        type plug
        slave.pcm "line-out"
    }
    capture.pcm {
        type plug
        slave.pcm "line-in"
    }
}

pcm.line-out {
    type plug
    slave {
        pcm "hw:h20aiao,0"
    }
}

pcm.line-in {
    type plug
    slave {
        pcm "hw:h20aiao,0"
    }
}