#!/bin/sh

linein_setup()
{
	# gpio0_a3
	#linein adctrl enable
	echo 3 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio3/direction
	echo 1 > /sys/class/gpio/gpio3/value
}

run_led_init()
{
	# gpio0_c4
	echo 20 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio20/direction
	echo 1 > /sys/class/gpio/gpio20/value
}

vrm()
{
	echo 4096 > /proc/sys/vm/min_free_kbytes
	echo 200 > /proc/sys/vm/vfs_cache_pressure
}

case "$1" in
	start)
		# ueventd
		#echo "bind irq 23 to cpu0"
		#echo 1 > /proc/irq/23/smp_affinity  (1,2,4,8对应0~3核, 23是usb中断号)
		#irqno=`cat /proc/interrupts | grep ff400000.usb | awk '{print $1}' | awk -F: '{print $1}'`
		#echo 8 > /proc/irq/$irqno/smp_affinity
		
		# linein_setup
		# run_led_init
		# vrm
		;;
	stop)
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
