#!/bin/sh

prepare_clk()
{
	echo "Initializing audio clock... Start"
	aplay -Dplug_dmix_h20aiao /dev/zero -fs16_le -r22050 -c2 -d 1
	echo "Initializing audio clock... End"
	# aplay -Dplug_dmix_h20aiao /dev/zero -fs16_le -r22050 -c2 &
	# PID=$!
	# sleep 1
	
	# if ps | grep -w "^\s*$PID" > /dev/null; then
	# 	kill -9 $PID 2>/dev/null
	# 	wait $PID 2>/dev/null
	# 	echo "Audio clock initialization completed"
	# else
	# 	echo "Warning: Failed to initialize audio clock"
	# fi
}

case "$1" in
	start)
		prepare_clk
		if [ -f /data/jdapp ]; then
			chmod +x /data/jdapp
			/data/jdapp verbose &
		else
			/usr/bin/jdapp &
		fi
		;;
	stop)
		killall -10 jdapp
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
