#!/bin/sh

case "$1" in
	start)
		if [ -f /data/jdapp ]; then
			if [ ! -x /data/jdapp ]; then
				chmod +x /data/jdapp
			fi
			/data/jdapp verbose &
		else
			/usr/bin/jdapp &
		fi
		;;
	stop)
		killall -10 jdapp
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
