defaults.pcm.rate_converter "speexrate_medium"
pcm.!default
{
    type asym
    playback.pcm {
        type plug
        slave.pcm "line-out"
    }
    capture.pcm {
        type plug
        slave.pcm "line-in"
    }
}

pcm.line-out {
    type plug
    slave {
        pcm "hw:rockchipti3104,0"
    }
}

pcm.line-in {
    type plug
    slave {
        pcm "hw:rockchipti3104,0"
    }
}

pcm.dmix_aiao {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:rockchipti3104,0"
        period_size 1024
        buffer_size 4096
    }
}