#!/bin/sh

passwd_init() {
	mkdir -p /data/console
	txt=`openssl passwd -1 ks_audio`
	awk -F ":" '{OFS=":"}{if ($1=="root") $2=''"'${txt}'"''}1' /etc/shadow > /data/console/shadow
	mount --bind /data/console/shadow /etc/shadow
}
case "$1" in
	start)
		# ueventd
		echo "bind irq 23 to cpu0"
		#echo 1 > /proc/irq/23/smp_affinity  (1,2,4,8对应0~3核, 23是usb中断号)
		irqno=`cat /proc/interrupts | grep ff400000.usb | awk '{print $1}' | awk -F: '{print $1}'`
		echo 8 > /proc/irq/$irqno/smp_affinity
		
		# 加载驱动
		echo "insmod board_ctrl.ko"
		insmod /usr/share/ko/board_ctrl.ko

		#调整为性能模式，始终工作在最高频率
		echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
		echo "scaling_governor is:"
		cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
		echo "scaling_cur_freq is:"
		cat /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq
		
		echo "download dsp firmware"
		echo 1 > /sys/ak7755_control/download_dsp_firmware
		amixer -c2 cset numid=20 0 > /dev/null
		amixer -c2 cset numid=11 231 > /dev/null #231
		amixer -c2 cset numid=12 231 > /dev/null
		amixer -c2 cset numid=15 off > /dev/null
		echo "set ref channel ADC ALC"
		# amixer -c 0 cget numid=61
		# amixer -c 0 cget numid=62
		# amixer -c 0 cset numid=61 6
		# amixer -c 0 cset numid=62 6
		aplay /opt/audio/zero.wav
		event.sh setvol 80
		echo 0 > /proc/sys/kernel/printk
		;;
	stop)
		# rmmod board_ctrl.ko
		# echo "rmmod board_ctrl.ko"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
