#!/bin/sh
case "$1" in
	start)
		# 修改CPU频率
		echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
		cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
		cat /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq
		# 使能PA
		echo 1 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio1/direction
		echo 0 > /sys/class/gpio/gpio1/value
		# printf "Starting play_zero: "
		# start-stop-daemon -S -q -m -b -p /var/run/play_zero.pid -x /usr/bin/play_zero.sh
		[ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
	stop)
		# printf "Stopping play_zero: "
		# start-stop-daemon -K -q -p /var/run/play_zero.pid
		[ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
