#!/bin/sh

case "$1" in
	start)
		if [ -f /data/jdapp ]; then
			chmod +x /data/jdapp
			/data/jdapp -r22050 -f16 -l256 &
		else
			/usr/bin/jdapp -r22050 -f16 -l256 &
		fi
		;;
	stop)
		killall -10 jdapp
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
